name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get -y install docker.io
        docker -v

    - name: Build Docker Image
      run: docker build -t my-python-app:latest .
      continue-on-error: true

    - name: Set up Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
        trivy -v

    - name: Scan Docker Image for Vulnerabilities with Trivy
      run: |
        trivy --config .trivy.yaml --exit-code 1 --severity HIGH,CRITICAL my-python-app:latest
      continue-on-error: true

