name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - featureBranch
  push:
    branches:
      - featureBranch

jobs:
  build:
    name: pre-merge-check
    runs-on: ubuntu-latest
    strategy:
  #    fail-fast: true
      matrix:
        language: ['python']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t nflask:v1 .
        docker image tag nflask:v1 mansi1811/nflask:v1

    # - name: Build Docker Image
    #   run: docker build -t nFlask:v1 .
    #   # continue-on-error: true

    - name: Set up Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
        trivy -v

    - name: Scan Docker Image for Vulnerabilities with Trivy
      run: |
        trivy image  --severity=HIGH nflask:v1
      # continue-on-error: false
      # if: ${{ success() }}

    # - name: Check vulnerability
    #   run: |
    #     trivy_output=$(trivy image  --severity=HIGH new:v1)
    #     if ${{ $trivy_output == 'Total: 0' }}
    #       echo 'No vulnerability '
    #     else
    #       exit 1
    #     fi
    - name: Convert Trivy Results to SARIF
      run: |
        trivy image --severity=HIGH,CRITICAL -f sarif nflask:v1 > trivy-results.sarif
      shell: bash
      if: always()

    - name: Upload SARIF Report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-results
        path: trivy-results.sarif
      if: always()
        
    - name: Push Docker Image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push mansi1811/new:v1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash
